const models = {
  drivers: {
    id: 0,
    model: "drivers",
    fields: [
      {
        name: "id",
        type: "number",
        readonly: true,
        placeholder: "",
        heading: "ID",
      },
      {
        name: "name",
        type: "text",
        readonly: false,
        placeholder: "driver name",
        heading: "Name",
      },
      {
        name: "number",
        type: "text",
        readonly: false,
        placeholder: "driver number",
        heading: "Nr",
      },
      {
        name: "team",
        type: "text",
        readonly: false,
        placeholder: "team",
        heading: "Team",
      },
      {
        name: "active",
        type: "checkbox",
        readonly: false,
        placeholder: "active",
        heading: "Active",
      },
    ],
  },
  teams: {
    id: 1,
    model: "teams",
    fields: [
      {
        name: "id",
        type: "number",
        readonly: true,
        placeholder: "",
        heading: "ID",
      },
      {
        name: "teamName",
        type: "text",
        readonly: false,
        placeholder: "team name",
        heading: "Name",
      },
      {
        name: "start",
        type: "text",
        readonly: false,
        placeholder: "start",
        heading: "Start",
      },
      {
        name: "active",
        type: "checkbox",
        readonly: false,
        placeholder: "team",
        heading: "Active",
      },
    ],
  },
  events: {
    id: 2,
    model: "events",
    fields: [
      {
        name: "id",
        type: "number",
        readonly: true,
        placeholder: "",
        heading: "ID",
      },
      {
        name: "name",
        type: "text",
        readonly: false,
        placeholder: "event name",
        heading: "Name",
      },
      {
        name: "raceStart",
        type: "date",
        readonly: false,
        placeholder: "race start",
        heading: "Race Start",
      },
      {
        name: "qualifyingStart",
        type: "text",
        readonly: false,
        placeholder: "qualifying start",
        heading: "Qualifying Start",
      },
      {
        name: "active",
        type: "checkbox",
        readonly: false,
        placeholder: "active",
        heading: "Active",
      },
    ],
  },
  results: {
    id: 3,
    fields: [
      {
        name: "id",
        type: "number",
        readonly: true,
        placeholder: "",
        heading: "ID",
      },
      {
        name: "name",
        type: "text",
        readonly: false,
        placeholder: "event name",
        heading: "Name",
      },
      {
        name: "pole",
        type: "text",
        readonly: false,
        placeholder: "pole position",
        heading: "pole Position",
      },
      {
        name: "F1Masters",
        type: "text",
        readonly: false,
        placeholder: "race start",
        heading: "Race Start",
      },
      {
        name: "Misc",
        type: "Boolean",
        readonly: false,
        placeholder: "misc",
        heading: "Misc",
      },
    ],
  },
};
export default models;
